name: flutter_validx
description: A beginner-friendly Flutter package that makes form validation clean and easy with prebuilt validators and ready-to-use input widgets.
version: 0.0.6
homepage: https://github.com/virajodedra/easy_form_validator
repository: https://github.com/virajodedra/easy_form_validator
example: example/example.dart

#issue_tracker: https://github.com/yourusername/easy_form_validator/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
# no assets needed
